---
title: "patent_applicants"
output: html_document
---

```{r load_packages}
library(sf)
library(sp)
library(geojson)
library(geojsonio)
library(tmap)
library(tmaptools)
library(tidyverse)
library(here)
library(janitor)
library(raster)
library(fpc)
library(rgdal)
library(ggplot2)
library(GGally)
library(plotly)
library(broom)
library(mapview)
library(crosstalk)
library(spdep)
library(car)
library(spatstat)
library(rgeos)
library(maptools)
library(GISTools)
library(dbscan)
```

```{r read_in_data}
# read in data
CN <- st_read(here::here("data", "map", "city_map",
                         "city.shp"))%>%
  st_transform(., 4480)%>%
  clean_names()

density <- read_csv(here::here("data", "clean", "density.csv"))%>%
  clean_names()%>%
  na.omit()

growth_rate <- read_csv(here::here("data", "clean", "growth_rate.csv"))%>%
  clean_names()%>%
  na.omit()
```

```{r join}
density_CN <- CN%>%
  left_join(.,
            density,
            by=c("shi_dai_ma"="city_code"))

growth_rate_CN <- CN%>%
  left_join(.,
            growth_rate,
            by=c("shi_dai_ma"="city_code"))
```

# density plot
```{r}
#natural breaks
tmap_mode("plot")
tmap_options(check.and.fix = TRUE)

t_2001 <- tm_shape(density_CN)+
  tm_polygons("x2001",
              #breaks=breaks,
              style="jenks",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2001 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2007 <- tm_shape(density_CN)+
  tm_polygons("x2007",
              #breaks=breaks,
              style="jenks",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2007 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2013 <- tm_shape(density_CN)+
  tm_polygons("x2013",
              #breaks=breaks,
              style="jenks",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2013 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2019 <- tm_shape(density_CN)+
  tm_polygons("x2019",
              #breaks=breaks,
              style="jenks",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2019 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2001
t_2007
t_2013
t_2019
```

```{r}
#quantile
tmap_mode("plot")
tmap_options(check.and.fix = TRUE)

t_2001_2 <- tm_shape(density_CN)+
  tm_polygons("x2001",
              #breaks=breaks,
              style="quantile",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2001 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2007_2 <- tm_shape(density_CN)+
  tm_polygons("x2007",
              #breaks=breaks,
              style="quantile",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2007 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2013_2 <- tm_shape(density_CN)+
  tm_polygons("x2013",
              #breaks=breaks,
              style="quantile",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2013 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2019_2 <- tm_shape(density_CN)+
  tm_polygons("x2019",
              #breaks=breaks,
              style="quantile",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2019 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2001_2
t_2007_2
t_2013_2
t_2019_2
```

```{r}
#decile
tmap_mode("plot")
tmap_options(check.and.fix = TRUE)

t_2001_3 <- tm_shape(density_CN)+
  tm_fill("x2001",
          #breaks=breaks,
          n=10,
          style="quantile",
          palette="PuBu",
          #midpoint=NA,#when there are minus values
          title="2001 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2007_3 <- tm_shape(density_CN)+
  tm_fill("x2007",
              #breaks=breaks,
          n=10,
              style="quantile",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2007 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2013_3 <- tm_shape(density_CN)+
  tm_fill("x2013",
              #breaks=breaks,
          n=10,
              style="quantile",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2013 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2019_3 <- tm_shape(density_CN)+
  tm_fill("x2019",
              #breaks=breaks,
          n=10,
              style="quantile",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2019 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2001_3
t_2007_3
t_2013_3
t_2019_3
```

```{r}
#equal intervals
tmap_mode("plot")
tmap_options(check.and.fix = TRUE)

t_2001_4 <- tm_shape(density_CN)+
  tm_polygons("x2001",
              #breaks=breaks,
              style="equal",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2001 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2007_4 <- tm_shape(density_CN)+
  tm_polygons("x2007",
              #breaks=breaks,
              style="equal",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2007 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2013_4 <- tm_shape(density_CN)+
  tm_polygons("x2013",
              #breaks=breaks,
              style="equal",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2013 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2019_4 <- tm_shape(density_CN)+
  tm_polygons("x2019",
              #breaks=breaks,
              style="equal",
              palette="PuBu",
              #midpoint=NA,#when there are minus values
              title="2019 Patent Applicants Density in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2001_4
t_2007_4
t_2013_4
t_2019_4
```

# growth rate plot
```{r growth_rate}
tmap_mode("plot")
tmap_options(check.and.fix = TRUE)

t_2001_2006 <- tm_shape(growth_rate_CN)+
  tm_polygons("x2001_2006",
              #breaks=breaks,
              style="jenks",
              palette="RdYlBu",
              #midpoint=NA,#when there are minus values
              title="2001-2006 Patent Applicants Growth Rate in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2006_2011 <- tm_shape(growth_rate_CN)+
  tm_polygons("x2006_2011",
              #breaks=breaks,
              style="jenks",
              palette="RdYlBu",
              #midpoint=NA,#when there are minus values
              title="2006-2011 Patent Applicants Growth Rate in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2011_2015 <- tm_shape(growth_rate_CN)+
  tm_polygons("x2011_2015",
              #breaks=breaks,
              style="jenks",
              palette="RdYlBu",
              #midpoint=NA,#when there are minus values
              title="2011-2015 Patent Applicants Growth Rate in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2015_2019 <- tm_shape(growth_rate_CN)+
  tm_polygons("x2015_2019",
              #breaks=breaks,
              style="jenks",
              palette="RdYlBu",
              #midpoint=NA,#when there are minus values
              title="2015-2019 Patent Applicants Growth Rate in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_2001_2006
t_2006_2011
t_2011_2015
t_2015_2019
```


```{r Global_spatial_autocorrelation_k_nearest_neighbor}
# calculate the centroids
coordsW <- density_CN%>%
  st_make_valid()%>%
  st_centroid()%>%
  st_geometry()
# Spatial weights matrix
# Relationship considerations: nearest neighbours
knn_wards <-coordsW %>%
  knearneigh(., k=4)
LWard_knn <- knn_wards %>%
  knn2nb()
plot(LWard_knn, st_geometry(coordsW), col="blue")
# Weight considerations: row standardization
Lward.knn_4_weight <- LWard_knn %>%
  nb2listw(., style="W")

# Moran's I of inventor density: clustered values (close to 1) or dispersed values (close to -1)
I_LWard_Global_2001 <- density_CN %>%
  pull(x2001) %>%
  as.vector()%>%
  moran.test(., Lward.knn_4_weight)

I_LWard_Global_2001

I_LWard_Global_2007 <- density_CN %>%
  pull(x2007) %>%
  as.vector()%>%
  moran.test(., Lward.knn_4_weight)

I_LWard_Global_2007

I_LWard_Global_2013 <- density_CN %>%
  pull(x2013) %>%
  as.vector()%>%
  moran.test(., Lward.knn_4_weight)

I_LWard_Global_2013

I_LWard_Global_2019 <- density_CN %>%
  pull(x2019) %>%
  as.vector()%>%
  moran.test(., Lward.knn_4_weight)

I_LWard_Global_2019
```

```{r Global_spatial_autocorrelation_queen_case}
# calculate the centroids
coordsW <- density_CN%>%
  st_make_valid()%>%
  st_centroid()%>%
  st_geometry()
# Spatial weights matrix
# Relationship considerations: queen
set.ZeroPolicyOption(TRUE)
#make weights matrix
queen.nb <- density_CN %>%
  st_make_valid()%>%
  poly2nb
# Weight considerations: row standardization
LWard_nb_weight <- queen.nb %>%
  nb2listw(., style="W", zero.policy = TRUE)

# Moran's I of inventor density: clustered values (close to 1) or dispersed values (close to -1)
I_LWard_Global_2001 <- density_CN %>%
  pull(x2001) %>%
  as.vector()%>%
  moran.test(., LWard_nb_weight, zero.policy = TRUE)

I_LWard_Global_2001
# Moran’s I is 0.05, meaning that there is some weak to moderate spatial autocorrelation in inventor density.

I_LWard_Global_2007 <- density_CN %>%
  pull(x2007) %>%
  as.vector()%>%
  moran.test(., LWard_nb_weight, zero.policy = TRUE)

I_LWard_Global_2007

I_LWard_Global_2013 <- density_CN %>%
  pull(x2013) %>%
  as.vector()%>%
  moran.test(., LWard_nb_weight, zero.policy = TRUE)

I_LWard_Global_2013

I_LWard_Global_2019 <- density_CN %>%
  pull(x2019) %>%
  as.vector()%>%
  moran.test(., LWard_nb_weight, zero.policy = TRUE)

I_LWard_Global_2019
```

# hotspots plot
```{r}
# Getis Ord Gi∗ of inventor density
Gi_LWard_Local_2001 <- density_CN %>%
  pull(x2001) %>%
  as.vector()%>%
  localG(., Lward.knn_4_weight)
density_CN <- density_CN %>%
  mutate(density_G_2001 = as.numeric(Gi_LWard_Local_2001))

Gi_LWard_Local_2007 <- density_CN %>%
  pull(x2007) %>%
  as.vector()%>%
  localG(., Lward.knn_4_weight)
density_CN <- density_CN %>%
  mutate(density_G_2007 = as.numeric(Gi_LWard_Local_2007))

Gi_LWard_Local_2013 <- density_CN %>%
  pull(x2013) %>%
  as.vector()%>%
  localG(., Lward.knn_4_weight)
density_CN <- density_CN %>%
  mutate(density_G_2013 = as.numeric(Gi_LWard_Local_2013))

Gi_LWard_Local_2019 <- density_CN %>%
  pull(x2019) %>%
  as.vector()%>%
  localG(., Lward.knn_4_weight)
density_CN <- density_CN %>%
  mutate(density_G_2019 = as.numeric(Gi_LWard_Local_2019))
```

```{r}
GIColours<- get_brewer_pal("RdBu")%>%
  rev()
t_gi_2001 <- tm_shape(density_CN) +
    tm_polygons("density_G_2001",
        style="jenks",
        palette=GIColours,
        midpoint=NA,
        title="Gi*, 2001 Patent Applicants in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_gi_2007 <- tm_shape(density_CN) +
    tm_polygons("density_G_2007",
        style="jenks",
        palette=GIColours,
        midpoint=NA,
        title="Gi*, 2007 Patent Applicants in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_gi_2013 <- tm_shape(density_CN) +
    tm_polygons("density_G_2013",
        style="jenks",
        palette=GIColours,
        midpoint=NA,
        title="Gi*, 2013 Patent Applicants in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_gi_2019 <- tm_shape(density_CN) +
    tm_polygons("density_G_2019",
        style="jenks",
        palette=GIColours,
        midpoint=NA,
        title="Gi*, 2019 Patent Applicants in China")+
  tm_layout(frame=FALSE,
            legend.outside=TRUE)+
  tm_compass(type = "arrow", size=1, position = c("left", "top")) +
  tm_scale_bar(position= c("left", "bottom"), text.size = .75)

t_gi_2001
t_gi_2007
t_gi_2013
t_gi_2019
```

# regression diagnostics
```{r}
library(AER)
library(plm)
library(stargazer)
library(lfe)
library(sandwich)
```

```{r}
#read in data
panel <- read_csv(here::here("data", "clean", "inventor_all_log.csv"))%>%
  clean_names()%>%
  na.omit()
```
```{r}
panel %>%
  is.pbalanced()
```

```{r}
# pooled
pooled <- plm(inventor_log ~ fdi_log+scicost_log+scipop_log+wage_log
          +unemp_log+unistu_log+studentteacher_log+docs_log
          +green_log+so2_log, data=panel,
          index=c("city","year"),
          model="pooling")
summary(pooled)
```

```{r}
# entity fixed
entity_fixed <- plm(inventor_log ~ fdi_log+scicost_log+scipop_log+wage_log
          +unemp_log+unistu_log+studentteacher_log+docs_log
          +green_log+so2_log, data=panel, 
          index=c("city","year"),
          effect="individual",
          model="within")
summary(entity_fixed)
```

```{r}
# time fixed
time_fixed <- plm(inventor_log ~ fdi_log+scicost_log+scipop_log+wage_log
          +unemp_log+unistu_log+studentteacher_log+docs_log
          +green_log+so2_log, data=panel, 
          index=c("city","year"),
          effect="time",
          model="within")
summary(time_fixed)
```

# tests
```{r}
# F test: fixed or pooled ols
pFtest(time_fixed, pooled)

# p-value is smaller than 0.05, indicating time fixed effects model is better than ols
```

```{r}
# random
random <- plm(inventor_log ~ fdi_log+scicost_log+scipop_log+wage_log
          +unemp_log+unistu_log+studentteacher_log+docs_log
          +green_log+so2_log, data=panel, 
          index=c("city","year"),
          effect="time",
          model="random")
summary(random)
```

```{r}
# Hausman test: fixed or random
phtest(time_fixed, random)

# p-value is smaller than 0.05, indicating fixed effects model is better than random effects model
```

# other diagnostics
```{r}
# Testing for cross-sectional dependence/contemporaneous correlation
# Breusch-Pagan LM test of independence and Pasaran CD test

#B-P/LM
pcdtest(time_fixed, test=c("lm"))
# p-value is smaller than 0.05, indicating there is cross-sectional dependence.

#Pasaran CD
pcdtest(time_fixed, test=c("cd"))
# p-value is smaller than 0.05, indicating there is cross-sectional dependence, which means the residuals are correlated across entities.

```

```{r}
#testing for serial correlation
pbgtest(time_fixed)
```

# spatial regression
```{r}
library(spatialreg)
library(rgdal)
library(spdep)
library(rgeos)
```

```{r}
#read in data
panel <- read_csv(here::here("data", "clean", "inventor_all_log.csv"))%>%
  clean_names()%>%
  na.omit()
```

```{r}
#join
panel_CN <- CN%>%
  inner_join(.,
            panel,
            by=c("shi_dai_ma"="city_code"))
```

```{r queen}
#make weights matrix
queen.nb <- panel_CN %>%
  st_make_valid()%>%
  poly2nb
#convert nb to listw type
queen.listw=nb2listw(queen.nb, zero.policy = TRUE)
listw1=queen.listw

reg.eq1=inventor_log ~ fdi_log+scicost_log+scipop_log+div_log+unemp_log+unistu_log+docs_log+green_log+so2_log
reg.eq2=inventor_log ~ fdi_log+scicost_log+scipop_log+div_log+unemp_log+unistu_log+docs_log+green_log+so2_log+fdi_div
reg.eq3=inventor_log ~ fdi_log+scicost_log+scipop_log+div_log+unemp_log+unistu_log+docs_log+green_log+so2_log+scicost_div
reg.eq4=inventor_log ~ fdi_log+scicost_log+scipop_log+div_log+unemp_log+unistu_log+docs_log+green_log+so2_log+scipop_div

```

# reg1
```{r}
#SEM Spatial Error Model
reg1=errorsarlm(reg.eq1, data=panel_CN, listw1)
summary(reg1)
tidy(reg1)
```

# reg2
```{r}
#SEM Spatial Error Model
reg2=errorsarlm(reg.eq2, data=panel_CN, listw1)
summary(reg2)
tidy(reg2)
```

# reg3
```{r}
reg3=errorsarlm(reg.eq3, data=panel_CN, listw1)
summary(reg3)
tidy(reg3)
```

# reg4
```{r}
reg4=errorsarlm(reg.eq4, data=panel_CN, listw1)
summary(reg4)
tidy(reg4)
```




